### ISSUE TITLE
Add generator for arguments global to all subcommands in cli template

### ISSUE THREAD

**Issue by tmattio** [tmattio/spin#39]
Here are some consideration to have when designing the solution:

- How can we provide the value with an env variable as well (the order of priority would be env variable -> cli argument -> default value)
- What is the best way to add arguments common to all sub-commands, while conserving the sub-commands separation, to use with spin gen cmd
- Can we create common arguments with a modular design? This would allow us to create a generator for the arguments (e.g. spin gen arg)

**Comment by citizen428** [comment]
> How can we provide the value with an env variable as well 

According to the [Cmdliner docs](https://erratique.ch/software/cmdliner/doc/Cmdliner.html) we sort of get the env variable for free, at least if the argument is not specified:

> Non-required command line arguments can be backed up by an environment variable. If the argument is absent from the command line and that the environment variable is defined, its value is parsed using the argument converter and defines the value of the argument.

> What is the best way to add arguments common to all sub-commands

The [Cmdliner examples](https://erratique.ch/software/cmdliner/doc/Cmdliner.html#examples) give an example of an application with a similar interface to DARCS, which handles this via a `copts` type and an accompanying `copts_t` term. I played around with this a bit, but since I'm not very familiar with the Spin codebase yet, I couldn't quite get it to work as intended.

**Comment by tmattio** [comment]
This issue does not make sense with the updated `cli` template in https://github.com/tmattio/spin/pull/74 since the common arguments can easily be added in the `common.ml` file. Closing now, the PR should be merged soon.
