### ISSUE TITLE
Error running `esy` on fresh ppx project

### ISSUE THREAD

**Issue by dylanirlbeck** [tmattio/spin#72]
So I created a new ppx project with

```
spin new ppx testing_ppx
```

and after running `esy` inside the directory I immediately got the following error:

```
$ esy
info esy 0.6.2 (using esy.json)
File "test/dune", line 6, characters 2-23:
6 |   (pps testingppx.lib))
      ^^^^^^^^^^^^^^^^^^^^^
Warning: .merlin generated is inaccurate. Cannot mix preprocessed and non
preprocessed specificiations.
Split the stanzas into different directories or silence this warning by
adding (allow_approximate_merlin) to your dune-project.
```

I solved the issue with `rm -rf test` but this doesn't seem like the right approach. Can I get some advice on how to solve this? Thanks in advance!

**Comment by tmattio** [comment]
Hi @dylanirlbeck!

Thanks for reporting the issue. The problem seems to be that the executable defined in `test/dune` does not have the `preprocess` stanza, whereas the library does. Apparently, dune handles this just fine, but merlin format is limited and can't find a way to represent this.

I made a PR to fix this, but I'm going to wait a bit before the next release of Spin. In the meantime, to remove the warning, you can add 
```
 (preprocess
  (pps testingppx.lib))
```
to the executable stanza in `test/dune`.

**Comment by dylanirlbeck** [comment]
Great, thanks!
