### ISSUE TITLE
Make Reason an optional dependency

### ISSUE THREAD

**Issue by shonfeder** [tmattio/spin#86]
The `Reason` dependency currently puts an upper limit on the ocaml compiler, and it adds some unneeded bloat for users who aren't interested in that syntax variant. Would it be possible to make `Reason` an optional dependency and, if so, would you open to this change?

**Comment by tmattio** [comment]
Hi @shonfeder!

I'm not familiar with how optional dependencies work, but if that's feasible without degrading the experience of Reason users, I'm 100% open to it!

Spin is also distributed as a standalone executable, an npm package, and a Homebrew package. You are not constrained by OCaml's upper limit with them. The last version is only available on Opam, but I will release it on the other installation platforms soon. As a workaround, if you're blocked by OCaml's version, I'd recommend switching to one of these in the meantime if that's possible for you 🙂

**Comment by shonfeder** [comment]
Thank you for the pointer to the other package managers!

If I get some some free cycles, I can look into adding the optionality. :)

**Comment by rgrinberg** [comment]
Today, I suggested to a user to use spin to quickly start with a project. Unfortunately, he had some problems installing it:

```
he following dependencies couldn't be met:  - spin -> reason -> ocaml < 4.11
ocaml --version: The OCaml toplevel, version 4.11.1
what does that even mean
it wants to downgrade my ocaml
```

If spin had a leaner dependency profile, issues like this could be avoided for opam users. I bet it would also make it easier to package spin for upstream distro users.

As a side note: I've been considering to to deprecated `dune init` and just tell users to use spin. This would be a much more attractive option if users could easily use spin with the latest version of OCaml using their preferred package manager.

**Comment by tmattio** [comment]
@rgrinberg Thanks for reporting the issue!

As you've experienced with the release of ocaml-lsp-server on opam, compatibility with the latest version of OCaml is blocked until Reason is released on opam. That's very unfortunate, but I don't see any alternative at the moment: Reason users constitute a large portion of Spin users, so dropping support for Reason is not an option. As I said, I am not very familiar with optional dependencies, but maybe you know a way to make the dependency on Reason optional? Like, is it possible to test for the presence of a library at compile time?

As I mentioned to @shonfeder, a workaround, for now, would be to install spin without opam. Users can use the installation script for instance. Another workaround would be to pin reason to their git repository, which is compatible with OCaml 4.11.

I'd also like to slim down the number of dependencies. Some of them can definitely be vendored (e.g. it's already the case of lambda-term), but I am not sure it would make sense to vendor Reason (because of its size), do you have any opinion on this?

> As a side note: I've been considering to to deprecated dune init and just tell users to use spin

I appreciate you considering spin as an alternative to `dune init`! I'm very open to suggestions/feature requests, so let me know if there's anything dune users would miss if they switched to spin, or if you had any feedback on `dune init` that you'd like to see implemented in spin.

**Comment by rgrinberg** [comment]
Why would dropping reason as a dependency degrade the experience for reason users of spin? The only thing that should matter to users is that reason/ocaml templates are available, right? It would just be a matter of running `refmt` in spin I think.

**Comment by tmattio** [comment]
You're right! Spin uses a custom implementation of refmt. I can't remember any good reason for this, so I could try removing the custom implementation and call `refmt` instead.

**Comment by tmattio** [comment]
Ah, actually the reason for this is that I wanted spin to be usable by users who don't have reason on their system.
Typically, `esy` users don't have Reason installed globally, it's only installed in their project's sandbox.

**Comment by rgrinberg** [comment]
And if that doesn't work, you could always just put your custom wrapper `spin-refmt` subpackage. As long as you can just call it as a binary.

**Comment by rgrinberg** [comment]
> Typically, esy users don't have Reason installed, it's only installed in their project's sandbox.

Seems like  you should be using the version of reason in their sandbox then 🤔 There are many versions of reason out there and it doesn't seem like it's possible to always use the one in spin.

**Comment by tmattio** [comment]
> Seems like you should be using the version of reason in their sandbox then

Great idea! Would be the same for opam projects actually, the workflow would to generate the project and install the dependencies first, then reformat the code and remove the `ml` files.
